### ISSUE TITLE
Adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [yosileyid/Document-Support-Bot#2]
Hey!
I am a beginner here and found this repository and noticed that the CONTRIBUTING file is empty

If it's ok, I would like to work on it

**Comment by yosileyid** [comment]
Certainly! A copy of our orgs contributing file can be found [here](https://github.com/hasidicdevs/Docs/blob/main/CONTRIBUTING.md) just head over and copy it and send me a PR. Thank you for the help 😃 feel free to join our discord server and join the team too.
